apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/spiffe/spire-tutorials/k8s/envoy-opa/k8s?ref=d27c579eb4f4e26f36f60373446c42c4ebd1e3da
  - otel-collector/
