$patch: merge
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  template:
    spec:
      containers:
        - name: opa
          args:
          - run
          - --server
          - --config-file=/run/opa/opa-config.yaml 
